### ISSUE TITLE
Tag Commits That Require Rebuild?

### ISSUE THREAD

**Issue by 0x0dada** [nimblemachines/muforth#8]
What do you think about including a boilerplate note/tag that shows up at start of git log for those commits which require a rebuild w/ ./configure.sh && make? Thinking it might be a little opaque for peeps who aren't familiar w/ muforth or muforth -> target relationship ...

**Comment by nimblemachines** [comment]
Yes, this is a good idea.

I could just put the text "[REBUILD]" in the commit title text, but it would nice if it could be made automatic and fool-proof.

I wonder if it can be done with a dot-file somewhere, so that if someone grabs the latest bits and just tries to run their old binary, somehow it will barf and tell them to rebuild?

Or a commit embedded in the C source that startup checks against its own?

I should think about this.
